<!doctype html>
<html lang="" >
<head>
	<title>HTMX Demos</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@next/css/pico.min.css"/>
	<script src="https://unpkg.com/htmx.org@1.9.4" crossorigin="anonymous"></script>
</head>

<body>
<main class="container">
	<h1>HTMX Demo Apps</h1>
	<header>
	</header>

	<ul>
		<li><a href="demo/spa/alpine-data/page1" target="_blank">Share data across pages with alpine-data</a> </li>
		<li><a href="demo/spa/alpine-store/page1" target="_blank">Share data across pages with alpine-store</a> </li>
	</ul>

</main>
</body>
</html>
