<article>
	<header>
		<h3>Tageszeit für Insulinempfindlichkeitsfaktor</h3>
	</header>
	<fieldset><label for="morning">
			<input type="radio" id="morning" name="size" value="morning" checked>
			Morgens
		</label>
		<label for="noon">
			<input type="radio" id="noon" name="size" value="noon">
			Mittags
		</label>
		<label for="evening">
			<input type="radio" id="evening" name="size" value="evening">
			Abends
		</label>
	</fieldset>
</article>
